#!/bin/bash
# Coolify entrypoint wrapper.
#
# Why this exists: upstream script.sh does `source ./.env.sample` as a fallback
# when ./.env is missing. With Coolify (or any setup that injects env vars via
# `environment:` instead of `env_file`), that fallback OVERWRITES the real
# values with the placeholder defaults from .env.sample (e.g.
# MYSQL_PASSWORD=cloudlogpassword), which then get written into
# application/config/database.php — breaking DB auth.
#
# This wrapper materialises a real .env file from the current environment
# BEFORE handing control to script.sh, so the source picks up the right values.

set -e

ENV_PATH="/var/www/html/.env"

# printf '%q' produces a shell-safe single-token form for any value, so the
# downstream `source .env` in script.sh can handle passwords with spaces,
# quotes, $, |, etc. without choking.
{
    printf 'MYSQL_ROOT_PASSWORD=%q\n' "${MYSQL_ROOT_PASSWORD}"
    printf 'MYSQL_DATABASE=%q\n'      "${MYSQL_DATABASE}"
    printf 'MYSQL_USER=%q\n'          "${MYSQL_USER}"
    printf 'MYSQL_PASSWORD=%q\n'      "${MYSQL_PASSWORD}"
    printf 'MYSQL_HOST=%q\n'          "${MYSQL_HOST:-db}"
    printf 'MYSQL_PORT=%q\n'          "${MYSQL_PORT:-3306}"
    printf 'BASE_LOCATOR=%q\n'        "${BASE_LOCATOR}"
    printf 'WEBSITE_URL=%q\n'         "${WEBSITE_URL}"
    printf 'DIRECTORY=%q\n'           "${DIRECTORY:-/var/www/html}"
} > "$ENV_PATH"

chmod 600 "$ENV_PATH"

# Self-heal application/config/database.php so its credentials match the
# runtime MYSQL_* env vars. Necessary on existing deployments whose
# database.php was generated by the upstream installer while it was still
# falling back to .env.sample defaults (the `cloudlogpassword` bug).
#
# Uses PHP rather than sed because the upstream sed substitution chokes on
# passwords containing |, & or \, while PHP escapes single-quoted literals
# correctly.
DB_CONFIG="/var/www/html/application/config/database.php"
if [ -f "$DB_CONFIG" ]; then
    PHP_FIX=$(mktemp /tmp/coolify-fix.XXXXXX.php)
    cat > "$PHP_FIX" <<'PHPSCRIPT'
<?php
$file = '/var/www/html/application/config/database.php';
if (!file_exists($file)) { exit(0); }
$content = file_get_contents($file);
$map = [
    'hostname' => getenv('MYSQL_HOST') ?: 'db',
    'username' => getenv('MYSQL_USER'),
    'password' => getenv('MYSQL_PASSWORD'),
    'database' => getenv('MYSQL_DATABASE'),
];
$changed = 0;
foreach ($map as $k => $v) {
    if ($v === false || $v === '') { continue; }
    $esc = str_replace(['\\', "'"], ['\\\\', "\\'"], $v);
    // preg_replace_callback avoids backreference interpretation in the
    // replacement string, which would corrupt passwords containing `\` or `$`.
    // Pattern matches a PHP single-quoted literal honouring \' and \\ escapes
    // so the rewrite is idempotent across restarts.
    $new = preg_replace_callback(
        "/'$k'\\s*=>\\s*'(?:\\\\.|[^'\\\\])*'/",
        function () use ($k, $esc) { return "'$k' => '$esc'"; },
        $content, -1, $count
    );
    if ($new !== null) { $content = $new; $changed += $count; }
}
file_put_contents($file, $content);
fwrite(STDERR, "[coolify-entrypoint] database.php fields synced: $changed\n");
PHPSCRIPT
    php "$PHP_FIX" || true
    rm -f "$PHP_FIX"
fi

exec /usr/local/bin/startup.sh
