#!/bin/bash
# Coolify entrypoint wrapper.
#
# Why this exists: upstream script.sh does `source ./.env.sample` as a fallback
# when ./.env is missing. With Coolify (or any setup that injects env vars via
# `environment:` instead of `env_file`), that fallback OVERWRITES the real
# values with the placeholder defaults from .env.sample (e.g.
# MYSQL_PASSWORD=cloudlogpassword), which then get written into
# application/config/database.php — breaking DB auth.
#
# This wrapper materialises a real .env file from the current environment
# BEFORE handing control to script.sh, so the source picks up the right values.

set -e

ENV_PATH="/var/www/html/.env"

# printf '%q' produces a shell-safe single-token form for any value, so the
# downstream `source .env` in script.sh can handle passwords with spaces,
# quotes, $, |, etc. without choking.
{
    printf 'MYSQL_ROOT_PASSWORD=%q\n' "${MYSQL_ROOT_PASSWORD}"
    printf 'MYSQL_DATABASE=%q\n'      "${MYSQL_DATABASE}"
    printf 'MYSQL_USER=%q\n'          "${MYSQL_USER}"
    printf 'MYSQL_PASSWORD=%q\n'      "${MYSQL_PASSWORD}"
    printf 'MYSQL_HOST=%q\n'          "${MYSQL_HOST:-db}"
    printf 'MYSQL_PORT=%q\n'          "${MYSQL_PORT:-3306}"
    printf 'BASE_LOCATOR=%q\n'        "${BASE_LOCATOR}"
    printf 'WEBSITE_URL=%q\n'         "${WEBSITE_URL}"
    printf 'DIRECTORY=%q\n'           "${DIRECTORY:-/var/www/html}"
} > "$ENV_PATH"

chmod 600 "$ENV_PATH"

# Self-heal application/config/database.php AND application/config/config.php
# so their credentials and URLs match the runtime env vars. Necessary on
# existing deployments whose configs were generated by the upstream installer
# while it was still falling back to .env.sample defaults (the
# `cloudlogpassword` bug, the `WEBSITE_URL=http://localhost` bug).
#
# Uses PHP rather than sed because the upstream sed substitution chokes on
# values containing |, & or \, while PHP can escape PHP string literals
# correctly.
DB_CONFIG="/var/www/html/application/config/database.php"
APP_CONFIG="/var/www/html/application/config/config.php"
if [ -f "$DB_CONFIG" ] || [ -f "$APP_CONFIG" ]; then
    PHP_FIX=$(mktemp /tmp/coolify-fix.XXXXXX.php)
    cat > "$PHP_FIX" <<'PHPSCRIPT'
<?php

/**
 * Patch a PHP config file by rewriting selected key→value assignments to
 * match runtime env vars. Handles single- and double-quoted literals and is
 * idempotent across restarts.
 *
 * @param string $file   Path to the PHP config file.
 * @param array  $map    keyName => desiredValue
 * @param string $shape  'arrow' for "'k' => 'v'" (database.php),
 *                       'config' for "$config['k'] = 'v'" (config.php).
 */
function patch_config(string $file, array $map, string $shape): int {
    if (!file_exists($file)) { return 0; }
    $content = file_get_contents($file);
    $changed = 0;
    foreach ($map as $k => $v) {
        if ($v === false || $v === '') { continue; }
        // Escape for a PHP single-quoted literal: \ → \\ and ' → \'
        $esc = str_replace(['\\', "'"], ['\\\\', "\\'"], $v);
        $kq  = preg_quote($k, '/');
        if ($shape === 'arrow') {
            // 'key' => 'value' or 'key' => "value"
            $pattern = '/' . "'" . $kq . "'" . '\s*=>\s*' .
                       '(?:' . "'" . '(?:\\\\.|[^' . "'" . '\\\\])*' . "'" .
                       '|"(?:\\\\.|[^"\\\\])*")/';
            $newLit  = "'$k' => '$esc'";
        } else { // 'config'
            // $config['key'] = 'value' or $config['key'] = "value"
            $pattern = '/\$config\[' . "'" . $kq . "'" . '\]\s*=\s*' .
                       '(?:' . "'" . '(?:\\\\.|[^' . "'" . '\\\\])*' . "'" .
                       '|"(?:\\\\.|[^"\\\\])*")/';
            $newLit  = "\$config['$k'] = '$esc'";
        }
        $new = preg_replace_callback(
            $pattern,
            function () use ($newLit) { return $newLit; },
            $content, -1, $count
        );
        if ($new !== null) { $content = $new; $changed += $count; }
    }
    file_put_contents($file, $content);
    return $changed;
}

$db_changed = patch_config(
    '/var/www/html/application/config/database.php',
    [
        'hostname' => getenv('MYSQL_HOST') ?: 'db',
        'username' => getenv('MYSQL_USER'),
        'password' => getenv('MYSQL_PASSWORD'),
        'database' => getenv('MYSQL_DATABASE'),
    ],
    'arrow'
);

// CodeIgniter base_url should end with a trailing slash; normalise.
$website = getenv('WEBSITE_URL') ?: '';
if ($website !== '' && substr($website, -1) !== '/') { $website .= '/'; }

$cfg_changed = patch_config(
    '/var/www/html/application/config/config.php',
    [
        'base_url'  => $website,
        'locator'   => getenv('BASE_LOCATOR') ?: '',
        'directory' => getenv('DIRECTORY') ?: '/var/www/html',
    ],
    'config'
);

fwrite(STDERR, "[coolify-entrypoint] database.php synced: $db_changed, config.php synced: $cfg_changed\n");
PHPSCRIPT
    php "$PHP_FIX" || true
    rm -f "$PHP_FIX"
fi

exec /usr/local/bin/startup.sh
